### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/sinatra-shotgun-server#1]
do it.

**Comment by AnnJohn** [comment]
from @dfenjves; you can pull content from this repo- https://github.com/learn-co-curriculum/sinatra-forms-params-readme-walkthrough

**Comment by AnnJohn** [comment]
@aviflombaum  deadline: 9/15/2015. Adding this to the spreadsheet.

**Comment by aviflombaum** [comment]
This is done. @AnnJohn can you update spreadsheets?
