### ISSUE TITLE
eventmachine-1.0.8 fails to install

### ISSUE THREAD

**Issue by c1505** [learn-co-curriculum/sinatra-shotgun-server#13]
Error and fix here https://github.com/eventmachine/eventmachine/issues/643
`brew link openssl --force` fixes it
It is an issue only on El Capitan OSX as far as I can tell.  
Also they say using eventmachine-1.0.9 fixes the problem.  I am not sure if bundle install would automatically use that version if there was no Gemfile.lock

**Comment by AnnJohn** [comment]
@vicfriedman this might be an engineering issue so feel free to unassign yourself if that's the case.
