### ISSUE TITLE
suggest adding additional sentence to README.md

### ISSUE THREAD

**Issue by agdavid** [learn-co-curriculum/sinatra-shotgun-server#16]
Hi LV team, consider adding the below **bold** sentence to the README.md to clarify that you need to refresh the browser, even when using shotgun: "Save your changes to app.rb and visit localhost:9393 in the browser. **Hit 'Refresh' in your browser to make a new request.** This time, you should see the text Started my server using shotgun! as opposed to seeing the previous text, just like with rackup."

**Comment by AnnJohn** [comment]
thanks for the suggestion @agdavid! 

@ruchiramani can you look at the suggestion raised in this issue and see if it's fine to update the readme with?
