### ISSUE TITLE
Forked the Lesson, But Sidebar Menu Does Not Reflect

### ISSUE THREAD

**Issue by wildcatblue** [learn-co-curriculum/sinatra-shotgun-server#20]
I have forked this lesson, both manually and through the "Open" button. However, the "Fork this lesson" part of the side menu does not turn green. I was able to submit a pull request, as seen in the picture below.

Because the "Fork this lesson" part of the menu is not marked successful, I am not able to complete this part of the lesson.

![screen shot 2016-07-05 at 12 28 18 pm](https://cloud.githubusercontent.com/assets/15336602/16573192/fcdb7c98-42ab-11e6-8cdd-818ffbb325c8.png)

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
