### ISSUE TITLE
Re: setup

### ISSUE THREAD

**Issue by dimacodes** [learn-co-curriculum/sinatra-shotgun-server#23]
Installing EventMachine via:

 "Make sure you run bundle install to install the gems in our Gemfile. If your operating system is OSX El Capitan, and you have an issue installing EventMachine, first check to make sure Open SSL is installed by entering brew install openssl in terminal. Once it's installed, enter brew link openssl --force" 

no longer works. 

Solution:
$ gem install eventmachine -- --with-cppflags=-I/usr/local/opt/openssl/include

Source: http://stackoverflow.com/questions/30818391/gem-eventmachine-fatal-error-openssl-ssl-h-file-not-found

**Comment by gj** [comment]
Thanks @dimitriwashere !
