### ISSUE TITLE
Kill rogue shotgun server

### ISSUE THREAD

**Issue by above9Sq** [learn-co-curriculum/sinatra-shotgun-server#25]
This may be helpful to others with the same issue.

I was unable to run shotgun because I had a connection somewhere else I was not aware of. I found this command that easily solved the issue. 

The basic process is: 
-you list open files
-you see the running shotfun server (with ID?)
-you kill that open file using the ID
-you are now able to run shotgun again for something else  

```
$ lsof -i TCP:9393   # shotgun starts on port 9393
=> ruby    53033 <a target="_blank" title="Stefan" href=" http://www.sdraht.com">Stefan</a>    5u  IPv4 0x15b4cb18      0t0  TCP localhost:9393 (LISTEN)
$ kill 53033
```

source: 
http://nimblespring.com/snippet-kill-a-rogue-server-process-in-terminal

**Comment by cjbrock** [comment]
Thanks for the feedback @JCesana! Hopefully this will help others if they have the same issue that you were having. 

// Corinna
