### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/sinatra-shotgun-server#26]
Should include the word "to" after "pass"-

"You can pass shotgun most of the CLI arguments and flags that rackup accepts."

**Comment by sgharms** [comment]
I'm going to respectfully disagree in this case. It's certainly not the case that all uses of "pass" require the dative construction.

* "You can pass (_no_) grandma the mashed potatoes."
* "You can pass 30% of your income _to_ Washington, thanks to the tax code."

But particularly common, and notable for our purposes, is the construction, as written like:

"[Pass the function an integer literal](https://factorpad.com/tech/python/reference/python-int.html)"

It's likely a usage discussion but my style guide has no ruling on it. And while I'm certainly no prescriptivist, if you have a rule (preferably Chicago style or MLA) that clarifies this ambiguity, we'll be happy to consider a change to our style guide.

My hypothesis here is that "to pass" already contains a dative thrust. Therefore when the indirect object is proximal to the verb, things read naturally ("Grandma," above). When there's a distance between the verb and the indirect object, we need to reassert the implied "to" of "pass" again ("to Washington," above).

**Comment by ode-to-the-code** [comment]
That's interesting to read! I like to flag typos but I don't know much
about grammar, at least not to that level. Sorry for the linguistic false
alarm

**Comment by sgharms** [comment]
We appreciate your careful reading and assure you that all suggestions are so similarly thoughtfully considered :)
