### ISSUE TITLE
Shotgun not compatible with IDES on Windows system

### ISSUE THREAD

**Issue by Jcg408** [learn-co-curriculum/sinatra-shotgun-server#28]
It would be nice if the lessons using shotgun advised that it is not compatible with Windows and some other gem/application should be used. I spent a lot of time trying to figure out why it wasn't working and eventually found a small section about it on StackOverflow. I prefer using my desktop  which is a larger system but it is Windows. Please notify students of issues with gems that are not supported in certain systems.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your contribution! We unfortunately, do not support native Windows at this time.
