### ISSUE TITLE
::Fixnum is deprecated 

### ISSUE THREAD

**Issue by blackwellsmith** [learn-co-curriculum/sinatra-shotgun-server#29]
So I can't do the code along.

**Comment by drakeltheryuujin** [comment]
Hi there,

I am able to complete this lesson, even with the warning `warning: constant ::Fixnum is deprecated`. I'm unable to reproduce any issues, so I'm going to close it for now.

If you can provide further detail about what is blocking you from completing this lesson, I'd be happy to take a second look!

As always, thanks for contributing! 💙
