### ISSUE TITLE
Knowledge gaps to address for students in the Learn Qualifying Track 

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/sinatra-shotgun-server#3]
![screen shot 2015-10-01 at 12 01 57 pm](https://cloud.githubusercontent.com/assets/1892150/10226226/42161bea-6834-11e5-8539-f3e205f4e011.png)

^^ Students won't know what a "gem" is. Is it worth a single line explanation? 

![screen shot 2015-10-01 at 12 04 12 pm](https://cloud.githubusercontent.com/assets/1892150/10226285/8edf126a-6834-11e5-845f-6d1039afa4af.png)

^^ "start our application server with rackup" is somewhat confusing. Would it be possible to visually (via code snippets or other things) or through an example to explain the paragraph after that. Explain better what or implications of reading code once on boot and never again is. 

![screen shot 2015-10-01 at 12 04 12 pm](https://cloud.githubusercontent.com/assets/1892150/10228002/a623d5e6-683e-11e5-9039-db5bbc08b069.png)

^^ Screenshot would be helpful

![screen shot 2015-10-01 at 12 04 12 pm](https://cloud.githubusercontent.com/assets/1892150/10228045/d1a71912-683e-11e5-98cc-dc2128aa827b.png)

In general showing a Sinatra app directory structure would be helpful. Also really going into detail about how to execute this would be good. Could this be turned into a codealong lab? 

Overall, I'm still pretty unclear at the end of this reading what shotgun actually is.

@matbalez

**Comment by victhevenot** [comment]
addressing in pull request
