### ISSUE TITLE
Shotgun gem 'No such file or directory'

### ISSUE THREAD

**Issue by DesterStorm** [learn-co-curriculum/sinatra-shotgun-server#30]
The shotgun gem isn't available for windows. I had to research this myself, but it would be nice if the lesson 'Using the Shotgun Development Server' mentioned that at the start. It would also be nice to have a shotgun replacement like rerun or instructions on running a Linux subsystem on windows such as: https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by sgharms** [comment]
Seems reasonable. The WSL has not yet proven itself stable for our labs, but we're excited about its development. Using our Linux VM for windows is a good way to avoid bumps. Full WSL support, now that it supports VSCode is definitely an exciting opportunity for the future.
