### ISSUE TITLE
Can't actually run shotgun

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/sinatra-shotgun-server#4]
Since this is a README and I'm not forking a repo to get code, I don't have a directory structure in which I can successfully run `shotgun`. I tried running it and it complained I did not have a config.ru file. It's not clear to me if I'm supposed to create such a file just to test that shotgun works?

**Comment by AnnJohn** [comment]
can we make this a codealong where we ask them to make a Sinatra directory (could build off the last readme). That way, they'll also get a pretty hands-on idea of the file structure of a Sinatra app

**Comment by jmburges** [comment]
Yeah love this idea. Give them a working app and make sure they are able to get it running. Probably won't have any tests or anything just make sure they understand shotgun before moving forward
